# -*- coding: utf-8 -*-
"""FMproject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DSvQkgkvJ0Ig1Z_g9QrlBv2QdO7SmGzW
"""

from google.colab import files
uploaded = files.upload()


import pandas as pd

# 讀入你的資料
df = pd.read_csv('Final_nflx_data_2018-2022.csv')

# 計算每日的「實際波動度」
# 計算當天的股價「波動度」，也就是價格的上下區間
df['volatility'] = df['High'] - df['Low']

# 加入 HAR 模型的變數
# rv1	前一天的波動度
# rv5	過去 5 天平均波動度（排除今天）
# rv10	過去 10 天平均波動度（排除今天）

df['rv1'] = df['volatility'].shift(1)
df['rv5'] = df['volatility'].rolling(window=5).mean().shift(1)
df['rv10'] = df['volatility'].rolling(window=10).mean().shift(1)
df['twt'] = df['twt_count'].shift(1)  # 使用昨天的推文數

# 清除缺值
df = df.dropna()

from sklearn.linear_model import LinearRegression
# scikit-learn 建立線性迴歸模型

# 選取特徵與標的值
# 根據 rv1, rv5, rv10, twt 預測當天的 volatility。
X = df[['rv1', 'rv5', 'rv10', 'twt']]
y = df['volatility']››

# 建立迴歸模型
model = LinearRegression()
model.fit(X, y)

# 印出迴歸係數
print("Intercept:", model.intercept_)
print("Coefficients:", model.coef_)

# 係數對應順序：rv1, rv5, rv10, twt
for name, coef in zip(X.columns, model.coef_):
    print(f"{name}: {coef:.6f}")